(defun for-dired ()
  (shrink-window-dired)
  (local-set-key (kbd "<RET>")
                 (lambda ()
                   (interactive)
                   (cond ((file-directory-p (thing-at-point 'filename))
                          (let ((previous (current-buffer)))
                            (dired-find-file)
                            (kill-buffer previous)))
                         (t
                          (dired-find-file-other-window))))))

(defun shrink-window-dired ()
  (cond ((eq (count-windows) 1)
         (split-window-horizontally)))
  (cond ((> (frame-width) 120)
         (shrink-window-horizontally (- (window-width) 10))
         (enlarge-window-horizontally (/ (frame-width) 4)))))
