(defmacro gsk-pairs-insert-macro (list)
  `(flet ((gsk (key command) (global-set-key key command)))
     (unless (null ,list)
       (gsk (caar ,list)
            (lambda ()
              (interactive)
              (cond ((region-active-p)
                     (let ((beginning (region-beginning))
                           (end (region-end)))
                       (goto-char beginning)
                       (insert (caar ,list))
                       (goto-char (+ end 1))
                       (insert (cdar ,list))))
                    (t
                     (insert (caar ,list) (cdar ,list))
                     (backward-char)))))
       (gsk-pairs-insert-macro (cdr ,list)))))

(defmacro gsk-key-function-macro (lists)
  `(unless (null ,lists)
     (global-set-key (caar ,lists) (cdar ,lists))
     (gsk-key-function-macro (cdr ,lists))))
